---
- hosts: all
  handlers:
  - import_tasks: ../handlers/apache-handlers.yml

  tasks:
  - name: Define facts the apache web server
    include: set_facts/apache-facts.yml
  
  - name: Install Apache HTTP web server as defined in facts
    package:
      name: "{{ packages }}"
      state: present
  
  - name: Use the preconfigured and included httpd conf file
    copy:
      src: ../files/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
    notify:
      - restart httpd
      
  - name: Create apache directories for installing
    file:
      path: "{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - /var/www/html/install
      - /var/www/html/ignition
      
  - name: Enable the apache server
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - "{{ services }}"