---
- hosts: all
  vars_files:
    - ../vars/nfs-config.yml 
   
  tasks:
    - name: Copy nfs-provisioner rbac file
      copy:
        src: ../files/nfs-auto-provisioner-rbac.yaml
        dest: /usr/local/src/nfs-auto-provisioner-rbac.yaml
        remote_src: yes
        owner: root
        group: root
        mode: 0666
    
    - name: Create the nfs-provisioner deployment config file from template
      template:
        src: ../templates/nfs-auto-provisioner-deployment.yaml.j2
        dest: /usr/local/src/nfs-auto-provisioner-deployment.yaml
        remote_src: yes
        owner: root
        group: root
        mode: 0666

    - name: Copy the nfs-provisioner storageclass
      copy:
        src: ../files/nfs-auto-provisioner-sc.yaml
        dest: /usr/local/src/nfs-auto-provisioner-sc.yaml
        remote_src: yes
        owner: root
        group: root
        mode: 0666

    - name: Copy the nfs-provisioner setup script
      copy:
        src: ../files/nfs-auto-provisioner-setup.sh
        dest: /usr/local/bin/nfs-auto-provisioner-setup.sh
        remote_src: yes
        owner: root
        group: root
        mode: 0555
    
    - name: Create an instance of the nfs provisioner
      shell: '/usr/local/bin/nfs-auto-provisioner-setup.sh --nfssharedir /export/shares/ocp-nfs --ocpns nfs-storage-provider --nfsprovisionername nfs-auto-provisioner'
