---
- block:
    - set_fact:
        packages:
          - nfs-utils
        
    - set_fact:
        services_enable:
          - nfs-server
          - rpcbind
    
    - set_fact:
        services_start:
          - nfs-server
          - rpcbind 
          - nfs-mountd
